version: '3.3'
services:
 LAPTOP-6HUMOL7G:
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=jose
   - MYSQL_PASSWORD=root
   - MYSQL_DATABASE=autoescuelaalpine
  restart: on-failure
  image: mysql:8.0.28-oracle
  volumes:
   - ./data/db:/var/lib/mysql
  user:
    mysql
  networks:
   - redalpine-network
 
 autoescuelaalpineinternosi1:
  build:
   context: .
   dockerfile: jarinterno.Dockerfile.txt
  restart: on-failure
  networks:
   - redalpine-network

 autoescuelaalpineinternosi2:
  build:
   context: .
   dockerfile: jarinterno.Dockerfile.txt
  restart: on-failure
  networks:
   - redalpine-network

 autoescuelaalpine:
  build:
   context: .
   dockerfile: jar.Dockerfile.txt
   args:
        nombreInstancia: autoescuelaalpine
  depends_on:
   - LAPTOP-6HUMOL7G
   - autoescuelaalpineinterno
  restart: on-failure
  networks:
   - redalpine-network     

 autoescuelaalpine2:
  build:
   context: .
   dockerfile: jar.Dockerfile.txt
   args:
        nombreInstancia: autoescuelaalpine2
  depends_on:
   - LAPTOP-6HUMOL7G
   - autoescuelaalpineinterno
  restart: on-failure
  networks:
   - redalpine-network

 haproxy:
  build:
   context: .
   dockerfile: haproxy.Dockerfile.txt
  depends_on:
   - LAPTOP-6HUMOL7G
   - autoescuelaalpineinterno
   - autoescuelaalpine
   - autoescuelaalpine2
  restart: on-failure
  ports:
   - 8443:8443
   - 1935:1935
  command: -f haproxy.cfg 
  networks:
   - redalpine-network

 autoescuelaalpineinterno:
  build:
   context: .
   dockerfile: haproxySI.Dockerfile.txt
  depends_on:
   - LAPTOP-6HUMOL7G
   - autoescuelaalpineinternosi1
   - autoescuelaalpineinternosi2
  restart: on-failure
  ports:
   - 1936:1936
  command: -f haproxySI.cfg 
  networks:
   - redalpine-network 
 
networks:
 redalpine-network:
  driver: bridge
  