version: '3.3'
services:
 LAPTOP-6HUMOL7G:
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=jose
   - MYSQL_PASSWORD=root
   - MYSQL_DATABASE=autoescuelaalpine
  image: mysql:8.0.28-oracle
  volumes:
   - ./data/db:/var/lib/mysql
 
 autoescuelaalpineinterno:
  build:
   context: .
   dockerfile: jarinterno.Dockerfile.txt

 autoescuelaalpine:
  build:
   context: .
   dockerfile: jar.Dockerfile.txt
  depends_on:
   - LAPTOP-6HUMOL7G
   - autoescuelaalpineinterno
      

 autoescuelaalpine2:
  build:
   context: .
   dockerfile: jar.Dockerfile.txt
  depends_on:
   - LAPTOP-6HUMOL7G
   - autoescuelaalpineinterno

 haproxy:
  build:
   context: .
   dockerfile: haproxy.Dockerfile.txt
  ports:
   - 8443:8443
  command: -f haproxy.cfg 
  depends_on:
   - LAPTOP-6HUMOL7G
   - autoescuelaalpineinterno
   - autoescuelaalpine
   - autoescuelaalpine2